//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Kaynak kodu Microsoft.VSDesigner tarafından otomatik üretilmiş , Sürüm 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GPTS.SKRS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSSKRSSistemlerPortBinding", Namespace="http://ws.esaglik.surat.com.tr/")]
    public partial class WSSKRSSistemlerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SistemlerOperationCompleted;
        
        private System.Threading.SendOrPostCallback SistemKodlariOperationCompleted;
        
        private System.Threading.SendOrPostCallback SistemKodlariSayfaGetirOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSSKRSSistemlerService() {
            this.Url = global::GPTS.Properties.Settings.Default.GPTS_SKRS_WSSKRSSistemlerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SistemlerCompletedEventHandler SistemlerCompleted;
        
        /// <remarks/>
        public event SistemKodlariCompletedEventHandler SistemKodlariCompleted;
        
        /// <remarks/>
        public event SistemKodlariSayfaGetirCompletedEventHandler SistemKodlariSayfaGetirCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.esaglik.surat.com.tr/", ResponseNamespace="http://ws.esaglik.surat.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("sistemlerOutput", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsskrsSistemlerResponse Sistemler() {
            object[] results = this.Invoke("Sistemler", new object[0]);
            return ((wsskrsSistemlerResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SistemlerAsync() {
            this.SistemlerAsync(null);
        }
        
        /// <remarks/>
        public void SistemlerAsync(object userState) {
            if ((this.SistemlerOperationCompleted == null)) {
                this.SistemlerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSistemlerOperationCompleted);
            }
            this.InvokeAsync("Sistemler", new object[0], this.SistemlerOperationCompleted, userState);
        }
        
        private void OnSistemlerOperationCompleted(object arg) {
            if ((this.SistemlerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SistemlerCompleted(this, new SistemlerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.esaglik.surat.com.tr/", ResponseNamespace="http://ws.esaglik.surat.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("sistemKodlariOutput", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public kodDegerleriResponse SistemKodlari([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string sistemKoduInput, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] System.DateTime tarihInput, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool tarihInputSpecified) {
            object[] results = this.Invoke("SistemKodlari", new object[] {
                        sistemKoduInput,
                        tarihInput,
                        tarihInputSpecified});
            return ((kodDegerleriResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SistemKodlariAsync(string sistemKoduInput, System.DateTime tarihInput, bool tarihInputSpecified) {
            this.SistemKodlariAsync(sistemKoduInput, tarihInput, tarihInputSpecified, null);
        }
        
        /// <remarks/>
        public void SistemKodlariAsync(string sistemKoduInput, System.DateTime tarihInput, bool tarihInputSpecified, object userState) {
            if ((this.SistemKodlariOperationCompleted == null)) {
                this.SistemKodlariOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSistemKodlariOperationCompleted);
            }
            this.InvokeAsync("SistemKodlari", new object[] {
                        sistemKoduInput,
                        tarihInput,
                        tarihInputSpecified}, this.SistemKodlariOperationCompleted, userState);
        }
        
        private void OnSistemKodlariOperationCompleted(object arg) {
            if ((this.SistemKodlariCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SistemKodlariCompleted(this, new SistemKodlariCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.esaglik.surat.com.tr/", ResponseNamespace="http://ws.esaglik.surat.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("sistemKodlariOutput", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public kodDegerleriResponse SistemKodlariSayfaGetir([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string sistemKoduInput, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] System.DateTime tarihInput, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool tarihInputSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int skrsKod, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool skrsKodSpecified) {
            object[] results = this.Invoke("SistemKodlariSayfaGetir", new object[] {
                        sistemKoduInput,
                        tarihInput,
                        tarihInputSpecified,
                        skrsKod,
                        skrsKodSpecified});
            return ((kodDegerleriResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SistemKodlariSayfaGetirAsync(string sistemKoduInput, System.DateTime tarihInput, bool tarihInputSpecified, int skrsKod, bool skrsKodSpecified) {
            this.SistemKodlariSayfaGetirAsync(sistemKoduInput, tarihInput, tarihInputSpecified, skrsKod, skrsKodSpecified, null);
        }
        
        /// <remarks/>
        public void SistemKodlariSayfaGetirAsync(string sistemKoduInput, System.DateTime tarihInput, bool tarihInputSpecified, int skrsKod, bool skrsKodSpecified, object userState) {
            if ((this.SistemKodlariSayfaGetirOperationCompleted == null)) {
                this.SistemKodlariSayfaGetirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSistemKodlariSayfaGetirOperationCompleted);
            }
            this.InvokeAsync("SistemKodlariSayfaGetir", new object[] {
                        sistemKoduInput,
                        tarihInput,
                        tarihInputSpecified,
                        skrsKod,
                        skrsKodSpecified}, this.SistemKodlariSayfaGetirOperationCompleted, userState);
        }
        
        private void OnSistemKodlariSayfaGetirOperationCompleted(object arg) {
            if ((this.SistemKodlariSayfaGetirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SistemKodlariSayfaGetirCompleted(this, new SistemKodlariSayfaGetirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esaglik.surat.com.tr/")]
    public partial class wsskrsSistemlerResponse {
        
        private hata hataField;
        
        private responseSistemler[] sistemlerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hata hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sistemler", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public responseSistemler[] sistemler {
            get {
                return this.sistemlerField;
            }
            set {
                this.sistemlerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esaglik.surat.com.tr/")]
    public partial class hata {
        
        private string yerelHataAciklamasiField;
        
        private hataTanimi hataTanimiField;
        
        private hataOgesi[] yerelHataListesiField;
        
        private string throwableStackTraceField;
        
        private string yerelHataKapsamiField;
        
        private string yerelHataKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string yerelHataAciklamasi {
            get {
                return this.yerelHataAciklamasiField;
            }
            set {
                this.yerelHataAciklamasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hataTanimi hataTanimi {
            get {
                return this.hataTanimiField;
            }
            set {
                this.hataTanimiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("hata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public hataOgesi[] yerelHataListesi {
            get {
                return this.yerelHataListesiField;
            }
            set {
                this.yerelHataListesiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string throwableStackTrace {
            get {
                return this.throwableStackTraceField;
            }
            set {
                this.throwableStackTraceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string yerelHataKapsami {
            get {
                return this.yerelHataKapsamiField;
            }
            set {
                this.yerelHataKapsamiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string yerelHataKodu {
            get {
                return this.yerelHataKoduField;
            }
            set {
                this.yerelHataKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esaglik.surat.com.tr/")]
    public partial class hataTanimi {
        
        private string genelHataAciklamasiField;
        
        private string genelHataKapsamiField;
        
        private string genelHataKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string genelHataAciklamasi {
            get {
                return this.genelHataAciklamasiField;
            }
            set {
                this.genelHataAciklamasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string genelHataKapsami {
            get {
                return this.genelHataKapsamiField;
            }
            set {
                this.genelHataKapsamiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string genelHataKodu {
            get {
                return this.genelHataKoduField;
            }
            set {
                this.genelHataKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esaglik.surat.com.tr/")]
    public partial class kodDegeriKolonIcerigi {
        
        private kodDegeriKolonIcerigiTipi kodDegeriKolonIcerigiTipiField;
        
        private bool kodDegeriKolonIcerigiTipiFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public kodDegeriKolonIcerigiTipi kodDegeriKolonIcerigiTipi {
            get {
                return this.kodDegeriKolonIcerigiTipiField;
            }
            set {
                this.kodDegeriKolonIcerigiTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool kodDegeriKolonIcerigiTipiSpecified {
            get {
                return this.kodDegeriKolonIcerigiTipiFieldSpecified;
            }
            set {
                this.kodDegeriKolonIcerigiTipiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esaglik.surat.com.tr/")]
    public enum kodDegeriKolonIcerigiTipi {
        
        /// <remarks/>
        NUMBER,
        
        /// <remarks/>
        BOOLEAN,
        
        /// <remarks/>
        TEXT,
        
        /// <remarks/>
        DATE,
        
        /// <remarks/>
        NULL,
        
        /// <remarks/>
        UNKNOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esaglik.surat.com.tr/")]
    public partial class kodDegeriKolonu {
        
        private kodDegeriKolonIcerigi kolonIcerigiField;
        
        private string kolonAdiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public kodDegeriKolonIcerigi kolonIcerigi {
            get {
                return this.kolonIcerigiField;
            }
            set {
                this.kolonIcerigiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string kolonAdi {
            get {
                return this.kolonAdiField;
            }
            set {
                this.kolonAdiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esaglik.surat.com.tr/")]
    public partial class kodDegerleriResponse {
        
        private hata hataField;
        
        private kodDegeriKolonu[][] kodDegerleriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hata hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("kodDegeriSatirlari", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("kodDegeriKolonlari", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, NestingLevel=1)]
        public kodDegeriKolonu[][] kodDegerleri {
            get {
                return this.kodDegerleriField;
            }
            set {
                this.kodDegerleriField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esaglik.surat.com.tr/")]
    public partial class responseSistemler {
        
        private string adiField;
        
        private bool aktifField;
        
        private bool aktifFieldSpecified;
        
        private System.DateTime guncellenmeTarihiField;
        
        private bool guncellenmeTarihiFieldSpecified;
        
        private hata hataField;
        
        private string hl7KoduField;
        
        private string koduField;
        
        private System.DateTime olusturulmaTarihiField;
        
        private bool olusturulmaTarihiFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string adi {
            get {
                return this.adiField;
            }
            set {
                this.adiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool aktif {
            get {
                return this.aktifField;
            }
            set {
                this.aktifField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aktifSpecified {
            get {
                return this.aktifFieldSpecified;
            }
            set {
                this.aktifFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime guncellenmeTarihi {
            get {
                return this.guncellenmeTarihiField;
            }
            set {
                this.guncellenmeTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool guncellenmeTarihiSpecified {
            get {
                return this.guncellenmeTarihiFieldSpecified;
            }
            set {
                this.guncellenmeTarihiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hata hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hl7Kodu {
            get {
                return this.hl7KoduField;
            }
            set {
                this.hl7KoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kodu {
            get {
                return this.koduField;
            }
            set {
                this.koduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime olusturulmaTarihi {
            get {
                return this.olusturulmaTarihiField;
            }
            set {
                this.olusturulmaTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool olusturulmaTarihiSpecified {
            get {
                return this.olusturulmaTarihiFieldSpecified;
            }
            set {
                this.olusturulmaTarihiFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esaglik.surat.com.tr/")]
    public partial class hataOgesi {
        
        private string hataAciklamasiField;
        
        private string hataKapsamiField;
        
        private string hataKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hataAciklamasi {
            get {
                return this.hataAciklamasiField;
            }
            set {
                this.hataAciklamasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hataKapsami {
            get {
                return this.hataKapsamiField;
            }
            set {
                this.hataKapsamiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hataKodu {
            get {
                return this.hataKoduField;
            }
            set {
                this.hataKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SistemlerCompletedEventHandler(object sender, SistemlerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SistemlerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SistemlerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsskrsSistemlerResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsskrsSistemlerResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SistemKodlariCompletedEventHandler(object sender, SistemKodlariCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SistemKodlariCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SistemKodlariCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public kodDegerleriResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((kodDegerleriResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SistemKodlariSayfaGetirCompletedEventHandler(object sender, SistemKodlariSayfaGetirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SistemKodlariSayfaGetirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SistemKodlariSayfaGetirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public kodDegerleriResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((kodDegerleriResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591