//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GPTS.wshitityazilim {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback kullanicilarOperationCompleted;
        
        private System.Threading.SendOrPostCallback KasaHareketleriOperationCompleted;
        
        private System.Threading.SendOrPostCallback destekOperationCompleted;
        
        private System.Threading.SendOrPostCallback KullanicilarRefOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemsGecenlerOperationCompleted;
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback KulEkleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DestekEkleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DestekGuncelleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DestekListOperationCompleted;
        
        private System.Threading.SendOrPostCallback DestekDetayEkleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DestekDetayListOperationCompleted;
        
        private System.Threading.SendOrPostCallback KulListOperationCompleted;
        
        private System.Threading.SendOrPostCallback EpostadanKulIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::GPTS.Properties.Settings.Default.GPTS_wshitityazilim_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetItemsCompletedEventHandler GetItemsCompleted;
        
        /// <remarks/>
        public event kullanicilarCompletedEventHandler kullanicilarCompleted;
        
        /// <remarks/>
        public event KasaHareketleriCompletedEventHandler KasaHareketleriCompleted;
        
        /// <remarks/>
        public event destekCompletedEventHandler destekCompleted;
        
        /// <remarks/>
        public event KullanicilarRefCompletedEventHandler KullanicilarRefCompleted;
        
        /// <remarks/>
        public event GetItemsGecenlerCompletedEventHandler GetItemsGecenlerCompleted;
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event KulEkleCompletedEventHandler KulEkleCompleted;
        
        /// <remarks/>
        public event DestekEkleCompletedEventHandler DestekEkleCompleted;
        
        /// <remarks/>
        public event DestekGuncelleCompletedEventHandler DestekGuncelleCompleted;
        
        /// <remarks/>
        public event DestekListCompletedEventHandler DestekListCompleted;
        
        /// <remarks/>
        public event DestekDetayEkleCompletedEventHandler DestekDetayEkleCompleted;
        
        /// <remarks/>
        public event DestekDetayListCompletedEventHandler DestekDetayListCompleted;
        
        /// <remarks/>
        public event KulListCompletedEventHandler KulListCompleted;
        
        /// <remarks/>
        public event EpostadanKulIdCompletedEventHandler EpostadanKulIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetItems() {
            object[] results = this.Invoke("GetItems", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemsAsync() {
            this.GetItemsAsync(null);
        }
        
        /// <remarks/>
        public void GetItemsAsync(object userState) {
            if ((this.GetItemsOperationCompleted == null)) {
                this.GetItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemsOperationCompleted);
            }
            this.InvokeAsync("GetItems", new object[0], this.GetItemsOperationCompleted, userState);
        }
        
        private void OnGetItemsOperationCompleted(object arg) {
            if ((this.GetItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemsCompleted(this, new GetItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/kullanicilar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string kullanicilar() {
            object[] results = this.Invoke("kullanicilar", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void kullanicilarAsync() {
            this.kullanicilarAsync(null);
        }
        
        /// <remarks/>
        public void kullanicilarAsync(object userState) {
            if ((this.kullanicilarOperationCompleted == null)) {
                this.kullanicilarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnkullanicilarOperationCompleted);
            }
            this.InvokeAsync("kullanicilar", new object[0], this.kullanicilarOperationCompleted, userState);
        }
        
        private void OnkullanicilarOperationCompleted(object arg) {
            if ((this.kullanicilarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.kullanicilarCompleted(this, new kullanicilarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KasaHareketleri", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string KasaHareketleri() {
            object[] results = this.Invoke("KasaHareketleri", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void KasaHareketleriAsync() {
            this.KasaHareketleriAsync(null);
        }
        
        /// <remarks/>
        public void KasaHareketleriAsync(object userState) {
            if ((this.KasaHareketleriOperationCompleted == null)) {
                this.KasaHareketleriOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKasaHareketleriOperationCompleted);
            }
            this.InvokeAsync("KasaHareketleri", new object[0], this.KasaHareketleriOperationCompleted, userState);
        }
        
        private void OnKasaHareketleriOperationCompleted(object arg) {
            if ((this.KasaHareketleriCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KasaHareketleriCompleted(this, new KasaHareketleriCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/destek", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string destek() {
            object[] results = this.Invoke("destek", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void destekAsync() {
            this.destekAsync(null);
        }
        
        /// <remarks/>
        public void destekAsync(object userState) {
            if ((this.destekOperationCompleted == null)) {
                this.destekOperationCompleted = new System.Threading.SendOrPostCallback(this.OndestekOperationCompleted);
            }
            this.InvokeAsync("destek", new object[0], this.destekOperationCompleted, userState);
        }
        
        private void OndestekOperationCompleted(object arg) {
            if ((this.destekCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.destekCompleted(this, new destekCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KullanicilarRef", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string KullanicilarRef() {
            object[] results = this.Invoke("KullanicilarRef", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void KullanicilarRefAsync() {
            this.KullanicilarRefAsync(null);
        }
        
        /// <remarks/>
        public void KullanicilarRefAsync(object userState) {
            if ((this.KullanicilarRefOperationCompleted == null)) {
                this.KullanicilarRefOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKullanicilarRefOperationCompleted);
            }
            this.InvokeAsync("KullanicilarRef", new object[0], this.KullanicilarRefOperationCompleted, userState);
        }
        
        private void OnKullanicilarRefOperationCompleted(object arg) {
            if ((this.KullanicilarRefCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KullanicilarRefCompleted(this, new KullanicilarRefCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItemsGecenler", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetItemsGecenler() {
            object[] results = this.Invoke("GetItemsGecenler", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemsGecenlerAsync() {
            this.GetItemsGecenlerAsync(null);
        }
        
        /// <remarks/>
        public void GetItemsGecenlerAsync(object userState) {
            if ((this.GetItemsGecenlerOperationCompleted == null)) {
                this.GetItemsGecenlerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemsGecenlerOperationCompleted);
            }
            this.InvokeAsync("GetItemsGecenler", new object[0], this.GetItemsGecenlerOperationCompleted, userState);
        }
        
        private void OnGetItemsGecenlerOperationCompleted(object arg) {
            if ((this.GetItemsGecenlerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemsGecenlerCompleted(this, new GetItemsGecenlerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld(string eposta) {
            object[] results = this.Invoke("HelloWorld", new object[] {
                        eposta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync(string eposta) {
            this.HelloWorldAsync(eposta, null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(string eposta, object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[] {
                        eposta}, this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KulEkle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string KulEkle(string kul_id, string kuladi, string aciklama, string eposta) {
            object[] results = this.Invoke("KulEkle", new object[] {
                        kul_id,
                        kuladi,
                        aciklama,
                        eposta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void KulEkleAsync(string kul_id, string kuladi, string aciklama, string eposta) {
            this.KulEkleAsync(kul_id, kuladi, aciklama, eposta, null);
        }
        
        /// <remarks/>
        public void KulEkleAsync(string kul_id, string kuladi, string aciklama, string eposta, object userState) {
            if ((this.KulEkleOperationCompleted == null)) {
                this.KulEkleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKulEkleOperationCompleted);
            }
            this.InvokeAsync("KulEkle", new object[] {
                        kul_id,
                        kuladi,
                        aciklama,
                        eposta}, this.KulEkleOperationCompleted, userState);
        }
        
        private void OnKulEkleOperationCompleted(object arg) {
            if ((this.KulEkleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KulEkleCompleted(this, new KulEkleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DestekEkle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DestekEkle(string kul_id, string eposta, string konu, string mesaj) {
            object[] results = this.Invoke("DestekEkle", new object[] {
                        kul_id,
                        eposta,
                        konu,
                        mesaj});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DestekEkleAsync(string kul_id, string eposta, string konu, string mesaj) {
            this.DestekEkleAsync(kul_id, eposta, konu, mesaj, null);
        }
        
        /// <remarks/>
        public void DestekEkleAsync(string kul_id, string eposta, string konu, string mesaj, object userState) {
            if ((this.DestekEkleOperationCompleted == null)) {
                this.DestekEkleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDestekEkleOperationCompleted);
            }
            this.InvokeAsync("DestekEkle", new object[] {
                        kul_id,
                        eposta,
                        konu,
                        mesaj}, this.DestekEkleOperationCompleted, userState);
        }
        
        private void OnDestekEkleOperationCompleted(object arg) {
            if ((this.DestekEkleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DestekEkleCompleted(this, new DestekEkleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DestekGuncelle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DestekGuncelle(string destek_id, string durumu) {
            object[] results = this.Invoke("DestekGuncelle", new object[] {
                        destek_id,
                        durumu});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DestekGuncelleAsync(string destek_id, string durumu) {
            this.DestekGuncelleAsync(destek_id, durumu, null);
        }
        
        /// <remarks/>
        public void DestekGuncelleAsync(string destek_id, string durumu, object userState) {
            if ((this.DestekGuncelleOperationCompleted == null)) {
                this.DestekGuncelleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDestekGuncelleOperationCompleted);
            }
            this.InvokeAsync("DestekGuncelle", new object[] {
                        destek_id,
                        durumu}, this.DestekGuncelleOperationCompleted, userState);
        }
        
        private void OnDestekGuncelleOperationCompleted(object arg) {
            if ((this.DestekGuncelleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DestekGuncelleCompleted(this, new DestekGuncelleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DestekList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable DestekList(string kul_id) {
            object[] results = this.Invoke("DestekList", new object[] {
                        kul_id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void DestekListAsync(string kul_id) {
            this.DestekListAsync(kul_id, null);
        }
        
        /// <remarks/>
        public void DestekListAsync(string kul_id, object userState) {
            if ((this.DestekListOperationCompleted == null)) {
                this.DestekListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDestekListOperationCompleted);
            }
            this.InvokeAsync("DestekList", new object[] {
                        kul_id}, this.DestekListOperationCompleted, userState);
        }
        
        private void OnDestekListOperationCompleted(object arg) {
            if ((this.DestekListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DestekListCompleted(this, new DestekListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DestekDetayEkle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DestekDetayEkle(string destekid, string detaymesaj) {
            object[] results = this.Invoke("DestekDetayEkle", new object[] {
                        destekid,
                        detaymesaj});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DestekDetayEkleAsync(string destekid, string detaymesaj) {
            this.DestekDetayEkleAsync(destekid, detaymesaj, null);
        }
        
        /// <remarks/>
        public void DestekDetayEkleAsync(string destekid, string detaymesaj, object userState) {
            if ((this.DestekDetayEkleOperationCompleted == null)) {
                this.DestekDetayEkleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDestekDetayEkleOperationCompleted);
            }
            this.InvokeAsync("DestekDetayEkle", new object[] {
                        destekid,
                        detaymesaj}, this.DestekDetayEkleOperationCompleted, userState);
        }
        
        private void OnDestekDetayEkleOperationCompleted(object arg) {
            if ((this.DestekDetayEkleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DestekDetayEkleCompleted(this, new DestekDetayEkleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DestekDetayList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable DestekDetayList(string id) {
            object[] results = this.Invoke("DestekDetayList", new object[] {
                        id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void DestekDetayListAsync(string id) {
            this.DestekDetayListAsync(id, null);
        }
        
        /// <remarks/>
        public void DestekDetayListAsync(string id, object userState) {
            if ((this.DestekDetayListOperationCompleted == null)) {
                this.DestekDetayListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDestekDetayListOperationCompleted);
            }
            this.InvokeAsync("DestekDetayList", new object[] {
                        id}, this.DestekDetayListOperationCompleted, userState);
        }
        
        private void OnDestekDetayListOperationCompleted(object arg) {
            if ((this.DestekDetayListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DestekDetayListCompleted(this, new DestekDetayListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KulList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable KulList() {
            object[] results = this.Invoke("KulList", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void KulListAsync() {
            this.KulListAsync(null);
        }
        
        /// <remarks/>
        public void KulListAsync(object userState) {
            if ((this.KulListOperationCompleted == null)) {
                this.KulListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKulListOperationCompleted);
            }
            this.InvokeAsync("KulList", new object[0], this.KulListOperationCompleted, userState);
        }
        
        private void OnKulListOperationCompleted(object arg) {
            if ((this.KulListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KulListCompleted(this, new KulListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EpostadanKulId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable EpostadanKulId(string eposta) {
            object[] results = this.Invoke("EpostadanKulId", new object[] {
                        eposta});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void EpostadanKulIdAsync(string eposta) {
            this.EpostadanKulIdAsync(eposta, null);
        }
        
        /// <remarks/>
        public void EpostadanKulIdAsync(string eposta, object userState) {
            if ((this.EpostadanKulIdOperationCompleted == null)) {
                this.EpostadanKulIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEpostadanKulIdOperationCompleted);
            }
            this.InvokeAsync("EpostadanKulId", new object[] {
                        eposta}, this.EpostadanKulIdOperationCompleted, userState);
        }
        
        private void OnEpostadanKulIdOperationCompleted(object arg) {
            if ((this.EpostadanKulIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EpostadanKulIdCompleted(this, new EpostadanKulIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetItemsCompletedEventHandler(object sender, GetItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void kullanicilarCompletedEventHandler(object sender, kullanicilarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class kullanicilarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal kullanicilarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void KasaHareketleriCompletedEventHandler(object sender, KasaHareketleriCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KasaHareketleriCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KasaHareketleriCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void destekCompletedEventHandler(object sender, destekCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class destekCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal destekCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void KullanicilarRefCompletedEventHandler(object sender, KullanicilarRefCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KullanicilarRefCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KullanicilarRefCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetItemsGecenlerCompletedEventHandler(object sender, GetItemsGecenlerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemsGecenlerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemsGecenlerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void KulEkleCompletedEventHandler(object sender, KulEkleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KulEkleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KulEkleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void DestekEkleCompletedEventHandler(object sender, DestekEkleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DestekEkleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DestekEkleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void DestekGuncelleCompletedEventHandler(object sender, DestekGuncelleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DestekGuncelleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DestekGuncelleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void DestekListCompletedEventHandler(object sender, DestekListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DestekListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DestekListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void DestekDetayEkleCompletedEventHandler(object sender, DestekDetayEkleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DestekDetayEkleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DestekDetayEkleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void DestekDetayListCompletedEventHandler(object sender, DestekDetayListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DestekDetayListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DestekDetayListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void KulListCompletedEventHandler(object sender, KulListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KulListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KulListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void EpostadanKulIdCompletedEventHandler(object sender, EpostadanKulIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EpostadanKulIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EpostadanKulIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591