//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPTS.yemeksepetiws {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="yemeksepetiws.IntegrationSoap")]
    public interface IntegrationSoap {
        
        // CODEGEN: GetMessageRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.GetMessageResponse GetMessage(GPTS.yemeksepetiws.GetMessageRequest request);
        
        // CODEGEN: GetMessageV2Request iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.GetMessageV2Response GetMessageV2(GPTS.yemeksepetiws.GetMessageV2Request request);
        
        // CODEGEN: GetAllMessagesRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.GetAllMessagesResponse GetAllMessages(GPTS.yemeksepetiws.GetAllMessagesRequest request);
        
        // CODEGEN: GetAllMessagesV2Request iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMessagesV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.GetAllMessagesV2Response GetAllMessagesV2(GPTS.yemeksepetiws.GetAllMessagesV2Request request);
        
        // CODEGEN: GetTopMessagesRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.GetTopMessagesResponse GetTopMessages(GPTS.yemeksepetiws.GetTopMessagesRequest request);
        
        // CODEGEN: GetTopMessagesV2Request iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopMessagesV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.GetTopMessagesV2Response GetTopMessagesV2(GPTS.yemeksepetiws.GetTopMessagesV2Request request);
        
        // CODEGEN: MessageSuccessfulRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MessageSuccessful", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.MessageSuccessfulResponse MessageSuccessful(GPTS.yemeksepetiws.MessageSuccessfulRequest request);
        
        // CODEGEN: UpdateOrderRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.UpdateOrderResponse UpdateOrder(GPTS.yemeksepetiws.UpdateOrderRequest request);
        
        // CODEGEN: UpdateValeOrderRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateValeOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.UpdateValeOrderResponse UpdateValeOrder(GPTS.yemeksepetiws.UpdateValeOrderRequest request);
        
        // CODEGEN: SetRestaurantForOrderRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetRestaurantForOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.SetRestaurantForOrderResponse SetRestaurantForOrder(GPTS.yemeksepetiws.SetRestaurantForOrderRequest request);
        
        // CODEGEN: GetRestaurantListRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRestaurantList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.GetRestaurantListResponse GetRestaurantList(GPTS.yemeksepetiws.GetRestaurantListRequest request);
        
        // CODEGEN: UpdateRestaurantStateRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRestaurantState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.UpdateRestaurantStateResponse UpdateRestaurantState(GPTS.yemeksepetiws.UpdateRestaurantStateRequest request);
        
        // CODEGEN: IsRestaurantOpenRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsRestaurantOpen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.IsRestaurantOpenResponse IsRestaurantOpen(GPTS.yemeksepetiws.IsRestaurantOpenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRestaurantStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.RestaurantStatusEntity GetRestaurantStatus(string catalogName, string categoryName);
        
        // CODEGEN: SetRestaurantServiceTimeRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetRestaurantServiceTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.SetRestaurantServiceTimeResponse SetRestaurantServiceTime(GPTS.yemeksepetiws.SetRestaurantServiceTimeRequest request);
        
        // CODEGEN: GetMenuRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMenu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.GetMenuResponse GetMenu(GPTS.yemeksepetiws.GetMenuRequest request);
        
        // CODEGEN: GetRestaurantPromotionsRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRestaurantPromotions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.GetRestaurantPromotionsResponse GetRestaurantPromotions(GPTS.yemeksepetiws.GetRestaurantPromotionsRequest request);
        
        // CODEGEN: GetRestaurantPointsAndCommentsRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRestaurantPointsAndComments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.GetRestaurantPointsAndCommentsResponse GetRestaurantPointsAndComments(GPTS.yemeksepetiws.GetRestaurantPointsAndCommentsRequest request);
        
        // CODEGEN: GetPaymentTypesRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaymentTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.GetPaymentTypesResponse GetPaymentTypes(GPTS.yemeksepetiws.GetPaymentTypesRequest request);
        
        // CODEGEN: GetRestaurantDeliveryAreasRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRestaurantDeliveryAreas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.GetRestaurantDeliveryAreasResponse GetRestaurantDeliveryAreas(GPTS.yemeksepetiws.GetRestaurantDeliveryAreasRequest request);
        
        // CODEGEN: UpdateRestaurantDeliveryAreaStateRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRestaurantDeliveryAreaState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPTS.yemeksepetiws.UpdateRestaurantDeliveryAreaStateResponse UpdateRestaurantDeliveryAreaState(GPTS.yemeksepetiws.UpdateRestaurantDeliveryAreaStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRestaurantOrderString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetRestaurantOrderString(string eadres, string trackingNo, string password);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RestaurantStatusEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string restaurantNameField;
        
        private string statusNameField;
        
        private string statusDescriptionField;
        
        private bool canBeOpenedByRestaurantField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RestaurantName {
            get {
                return this.restaurantNameField;
            }
            set {
                this.restaurantNameField = value;
                this.RaisePropertyChanged("RestaurantName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusName {
            get {
                return this.statusNameField;
            }
            set {
                this.statusNameField = value;
                this.RaisePropertyChanged("StatusName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
                this.RaisePropertyChanged("StatusDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool CanBeOpenedByRestaurant {
            get {
                return this.canBeOpenedByRestaurantField;
            }
            set {
                this.canBeOpenedByRestaurantField = value;
                this.RaisePropertyChanged("CanBeOpenedByRestaurant");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        public GetMessageRequest() {
        }
        
        public GetMessageRequest(GPTS.yemeksepetiws.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetMessageResult;
        
        public GetMessageResponse() {
        }
        
        public GetMessageResponse(string GetMessageResult) {
            this.GetMessageResult = GetMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageV2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMessageV2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        public GetMessageV2Request() {
        }
        
        public GetMessageV2Request(GPTS.yemeksepetiws.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageV2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMessageV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetMessageV2Result;
        
        public GetMessageV2Response() {
        }
        
        public GetMessageV2Response(string GetMessageV2Result) {
            this.GetMessageV2Result = GetMessageV2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllMessages", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllMessagesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        public GetAllMessagesRequest() {
        }
        
        public GetAllMessagesRequest(GPTS.yemeksepetiws.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllMessagesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetAllMessagesResult;
        
        public GetAllMessagesResponse() {
        }
        
        public GetAllMessagesResponse(string GetAllMessagesResult) {
            this.GetAllMessagesResult = GetAllMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllMessagesV2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllMessagesV2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        public GetAllMessagesV2Request() {
        }
        
        public GetAllMessagesV2Request(GPTS.yemeksepetiws.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllMessagesV2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllMessagesV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetAllMessagesV2Result;
        
        public GetAllMessagesV2Response() {
        }
        
        public GetAllMessagesV2Response(string GetAllMessagesV2Result) {
            this.GetAllMessagesV2Result = GetAllMessagesV2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTopMessages", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTopMessagesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int count;
        
        public GetTopMessagesRequest() {
        }
        
        public GetTopMessagesRequest(GPTS.yemeksepetiws.AuthHeader AuthHeader, int count) {
            this.AuthHeader = AuthHeader;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTopMessagesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTopMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetTopMessagesResult;
        
        public GetTopMessagesResponse() {
        }
        
        public GetTopMessagesResponse(string GetTopMessagesResult) {
            this.GetTopMessagesResult = GetTopMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTopMessagesV2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTopMessagesV2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int count;
        
        public GetTopMessagesV2Request() {
        }
        
        public GetTopMessagesV2Request(GPTS.yemeksepetiws.AuthHeader AuthHeader, int count) {
            this.AuthHeader = AuthHeader;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTopMessagesV2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTopMessagesV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetTopMessagesV2Result;
        
        public GetTopMessagesV2Response() {
        }
        
        public GetTopMessagesV2Response(string GetTopMessagesV2Result) {
            this.GetTopMessagesV2Result = GetTopMessagesV2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MessageSuccessful", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MessageSuccessfulRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int messageId;
        
        public MessageSuccessfulRequest() {
        }
        
        public MessageSuccessfulRequest(GPTS.yemeksepetiws.AuthHeader AuthHeader, int messageId) {
            this.AuthHeader = AuthHeader;
            this.messageId = messageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MessageSuccessfulResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MessageSuccessfulResponse {
        
        public MessageSuccessfulResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum OrderStates {
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        Rejected,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        OnDelivery,
        
        /// <remarks/>
        Delivered,
        
        /// <remarks/>
        TechnicalRejected,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateOrder", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal orderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public GPTS.yemeksepetiws.OrderStates orderState;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string reason;
        
        public UpdateOrderRequest() {
        }
        
        public UpdateOrderRequest(GPTS.yemeksepetiws.AuthHeader AuthHeader, decimal orderId, GPTS.yemeksepetiws.OrderStates orderState, string reason) {
            this.AuthHeader = AuthHeader;
            this.orderId = orderId;
            this.orderState = orderState;
            this.reason = reason;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateOrderResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UpdateOrderResult;
        
        public UpdateOrderResponse() {
        }
        
        public UpdateOrderResponse(string UpdateOrderResult) {
            this.UpdateOrderResult = UpdateOrderResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum PrepareTimes {
        
        /// <remarks/>
        Minutes_15,
        
        /// <remarks/>
        Minutes_20,
        
        /// <remarks/>
        Minutes_25,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateValeOrder", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateValeOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal orderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public GPTS.yemeksepetiws.OrderStates orderState;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<PrepareTimes> prepareTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string reason;
        
        public UpdateValeOrderRequest() {
        }
        
        public UpdateValeOrderRequest(GPTS.yemeksepetiws.AuthHeader AuthHeader, decimal orderId, GPTS.yemeksepetiws.OrderStates orderState, System.Nullable<PrepareTimes> prepareTime, string reason) {
            this.AuthHeader = AuthHeader;
            this.orderId = orderId;
            this.orderState = orderState;
            this.prepareTime = prepareTime;
            this.reason = reason;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateValeOrderResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateValeOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UpdateValeOrderResult;
        
        public UpdateValeOrderResponse() {
        }
        
        public UpdateValeOrderResponse(string UpdateValeOrderResult) {
            this.UpdateValeOrderResult = UpdateValeOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetRestaurantForOrder", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetRestaurantForOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal orderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string categoryName;
        
        public SetRestaurantForOrderRequest() {
        }
        
        public SetRestaurantForOrderRequest(GPTS.yemeksepetiws.AuthHeader AuthHeader, decimal orderId, string categoryName) {
            this.AuthHeader = AuthHeader;
            this.orderId = orderId;
            this.categoryName = categoryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetRestaurantForOrderResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetRestaurantForOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SetRestaurantForOrderResult;
        
        public SetRestaurantForOrderResponse() {
        }
        
        public SetRestaurantForOrderResponse(bool SetRestaurantForOrderResult) {
            this.SetRestaurantForOrderResult = SetRestaurantForOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRestaurantList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRestaurantListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        public GetRestaurantListRequest() {
        }
        
        public GetRestaurantListRequest(GPTS.yemeksepetiws.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRestaurantListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRestaurantListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetRestaurantListResult;
        
        public GetRestaurantListResponse() {
        }
        
        public GetRestaurantListResponse(System.Data.DataSet GetRestaurantListResult) {
            this.GetRestaurantListResult = GetRestaurantListResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum RestaurantStates {
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Closed,
        
        /// <remarks/>
        HugeDemand,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRestaurantState", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateRestaurantStateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string catalogName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string categoryName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public GPTS.yemeksepetiws.RestaurantStates restaurantState;
        
        public UpdateRestaurantStateRequest() {
        }
        
        public UpdateRestaurantStateRequest(GPTS.yemeksepetiws.AuthHeader AuthHeader, string catalogName, string categoryName, GPTS.yemeksepetiws.RestaurantStates restaurantState) {
            this.AuthHeader = AuthHeader;
            this.catalogName = catalogName;
            this.categoryName = categoryName;
            this.restaurantState = restaurantState;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRestaurantStateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateRestaurantStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UpdateRestaurantStateResult;
        
        public UpdateRestaurantStateResponse() {
        }
        
        public UpdateRestaurantStateResponse(string UpdateRestaurantStateResult) {
            this.UpdateRestaurantStateResult = UpdateRestaurantStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsRestaurantOpen", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsRestaurantOpenRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string catalogName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string categoryName;
        
        public IsRestaurantOpenRequest() {
        }
        
        public IsRestaurantOpenRequest(GPTS.yemeksepetiws.AuthHeader AuthHeader, string catalogName, string categoryName) {
            this.AuthHeader = AuthHeader;
            this.catalogName = catalogName;
            this.categoryName = categoryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsRestaurantOpenResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsRestaurantOpenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool IsRestaurantOpenResult;
        
        public IsRestaurantOpenResponse() {
        }
        
        public IsRestaurantOpenResponse(bool IsRestaurantOpenResult) {
            this.IsRestaurantOpenResult = IsRestaurantOpenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetRestaurantServiceTime", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetRestaurantServiceTimeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string catalogName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string categoryName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int serviceTime;
        
        public SetRestaurantServiceTimeRequest() {
        }
        
        public SetRestaurantServiceTimeRequest(GPTS.yemeksepetiws.AuthHeader AuthHeader, string catalogName, string categoryName, int serviceTime) {
            this.AuthHeader = AuthHeader;
            this.catalogName = catalogName;
            this.categoryName = categoryName;
            this.serviceTime = serviceTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetRestaurantServiceTimeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetRestaurantServiceTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SetRestaurantServiceTimeResult;
        
        public SetRestaurantServiceTimeResponse() {
        }
        
        public SetRestaurantServiceTimeResponse(bool SetRestaurantServiceTimeResult) {
            this.SetRestaurantServiceTimeResult = SetRestaurantServiceTimeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenu", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMenuRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        public GetMenuRequest() {
        }
        
        public GetMenuRequest(GPTS.yemeksepetiws.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMenuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetMenuResult;
        
        public GetMenuResponse() {
        }
        
        public GetMenuResponse(System.Data.DataSet GetMenuResult) {
            this.GetMenuResult = GetMenuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRestaurantPromotions", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRestaurantPromotionsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        public GetRestaurantPromotionsRequest() {
        }
        
        public GetRestaurantPromotionsRequest(GPTS.yemeksepetiws.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRestaurantPromotionsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRestaurantPromotionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetRestaurantPromotionsResult;
        
        public GetRestaurantPromotionsResponse() {
        }
        
        public GetRestaurantPromotionsResponse(System.Data.DataSet GetRestaurantPromotionsResult) {
            this.GetRestaurantPromotionsResult = GetRestaurantPromotionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRestaurantPointsAndComments", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRestaurantPointsAndCommentsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string catalogName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string categoryName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.DateTime endDate;
        
        public GetRestaurantPointsAndCommentsRequest() {
        }
        
        public GetRestaurantPointsAndCommentsRequest(GPTS.yemeksepetiws.AuthHeader AuthHeader, string catalogName, string categoryName, System.DateTime startDate, System.DateTime endDate) {
            this.AuthHeader = AuthHeader;
            this.catalogName = catalogName;
            this.categoryName = categoryName;
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRestaurantPointsAndCommentsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRestaurantPointsAndCommentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable GetRestaurantPointsAndCommentsResult;
        
        public GetRestaurantPointsAndCommentsResponse() {
        }
        
        public GetRestaurantPointsAndCommentsResponse(System.Data.DataTable GetRestaurantPointsAndCommentsResult) {
            this.GetRestaurantPointsAndCommentsResult = GetRestaurantPointsAndCommentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaymentTypes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPaymentTypesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        public GetPaymentTypesRequest() {
        }
        
        public GetPaymentTypesRequest(GPTS.yemeksepetiws.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaymentTypesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPaymentTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetPaymentTypesResult;
        
        public GetPaymentTypesResponse() {
        }
        
        public GetPaymentTypesResponse(System.Data.DataSet GetPaymentTypesResult) {
            this.GetPaymentTypesResult = GetPaymentTypesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRestaurantDeliveryAreas", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRestaurantDeliveryAreasRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string catalogName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string categoryName;
        
        public GetRestaurantDeliveryAreasRequest() {
        }
        
        public GetRestaurantDeliveryAreasRequest(GPTS.yemeksepetiws.AuthHeader AuthHeader, string catalogName, string categoryName) {
            this.AuthHeader = AuthHeader;
            this.catalogName = catalogName;
            this.categoryName = categoryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRestaurantDeliveryAreasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRestaurantDeliveryAreasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetRestaurantDeliveryAreasResult;
        
        public GetRestaurantDeliveryAreasResponse() {
        }
        
        public GetRestaurantDeliveryAreasResponse(System.Data.DataSet GetRestaurantDeliveryAreasResult) {
            this.GetRestaurantDeliveryAreasResult = GetRestaurantDeliveryAreasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRestaurantDeliveryAreaState", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateRestaurantDeliveryAreaStateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GPTS.yemeksepetiws.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string catalogName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string categoryName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string areaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public bool isOpen;
        
        public UpdateRestaurantDeliveryAreaStateRequest() {
        }
        
        public UpdateRestaurantDeliveryAreaStateRequest(GPTS.yemeksepetiws.AuthHeader AuthHeader, string catalogName, string categoryName, string areaId, bool isOpen) {
            this.AuthHeader = AuthHeader;
            this.catalogName = catalogName;
            this.categoryName = categoryName;
            this.areaId = areaId;
            this.isOpen = isOpen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRestaurantDeliveryAreaStateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateRestaurantDeliveryAreaStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateRestaurantDeliveryAreaStateResult;
        
        public UpdateRestaurantDeliveryAreaStateResponse() {
        }
        
        public UpdateRestaurantDeliveryAreaStateResponse(bool UpdateRestaurantDeliveryAreaStateResult) {
            this.UpdateRestaurantDeliveryAreaStateResult = UpdateRestaurantDeliveryAreaStateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IntegrationSoapChannel : GPTS.yemeksepetiws.IntegrationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegrationSoapClient : System.ServiceModel.ClientBase<GPTS.yemeksepetiws.IntegrationSoap>, GPTS.yemeksepetiws.IntegrationSoap {
        
        public IntegrationSoapClient() {
        }
        
        public IntegrationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegrationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.GetMessageResponse GPTS.yemeksepetiws.IntegrationSoap.GetMessage(GPTS.yemeksepetiws.GetMessageRequest request) {
            return base.Channel.GetMessage(request);
        }
        
        public string GetMessage(GPTS.yemeksepetiws.AuthHeader AuthHeader) {
            GPTS.yemeksepetiws.GetMessageRequest inValue = new GPTS.yemeksepetiws.GetMessageRequest();
            inValue.AuthHeader = AuthHeader;
            GPTS.yemeksepetiws.GetMessageResponse retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).GetMessage(inValue);
            return retVal.GetMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.GetMessageV2Response GPTS.yemeksepetiws.IntegrationSoap.GetMessageV2(GPTS.yemeksepetiws.GetMessageV2Request request) {
            return base.Channel.GetMessageV2(request);
        }
        
        public string GetMessageV2(GPTS.yemeksepetiws.AuthHeader AuthHeader) {
            GPTS.yemeksepetiws.GetMessageV2Request inValue = new GPTS.yemeksepetiws.GetMessageV2Request();
            inValue.AuthHeader = AuthHeader;
            GPTS.yemeksepetiws.GetMessageV2Response retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).GetMessageV2(inValue);
            return retVal.GetMessageV2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.GetAllMessagesResponse GPTS.yemeksepetiws.IntegrationSoap.GetAllMessages(GPTS.yemeksepetiws.GetAllMessagesRequest request) {
            return base.Channel.GetAllMessages(request);
        }
        
        public string GetAllMessages(GPTS.yemeksepetiws.AuthHeader AuthHeader) {
            GPTS.yemeksepetiws.GetAllMessagesRequest inValue = new GPTS.yemeksepetiws.GetAllMessagesRequest();
            inValue.AuthHeader = AuthHeader;
            GPTS.yemeksepetiws.GetAllMessagesResponse retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).GetAllMessages(inValue);
            return retVal.GetAllMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.GetAllMessagesV2Response GPTS.yemeksepetiws.IntegrationSoap.GetAllMessagesV2(GPTS.yemeksepetiws.GetAllMessagesV2Request request) {
            return base.Channel.GetAllMessagesV2(request);
        }
        
        public string GetAllMessagesV2(GPTS.yemeksepetiws.AuthHeader AuthHeader) {
            GPTS.yemeksepetiws.GetAllMessagesV2Request inValue = new GPTS.yemeksepetiws.GetAllMessagesV2Request();
            inValue.AuthHeader = AuthHeader;
            GPTS.yemeksepetiws.GetAllMessagesV2Response retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).GetAllMessagesV2(inValue);
            return retVal.GetAllMessagesV2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.GetTopMessagesResponse GPTS.yemeksepetiws.IntegrationSoap.GetTopMessages(GPTS.yemeksepetiws.GetTopMessagesRequest request) {
            return base.Channel.GetTopMessages(request);
        }
        
        public string GetTopMessages(GPTS.yemeksepetiws.AuthHeader AuthHeader, int count) {
            GPTS.yemeksepetiws.GetTopMessagesRequest inValue = new GPTS.yemeksepetiws.GetTopMessagesRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.count = count;
            GPTS.yemeksepetiws.GetTopMessagesResponse retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).GetTopMessages(inValue);
            return retVal.GetTopMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.GetTopMessagesV2Response GPTS.yemeksepetiws.IntegrationSoap.GetTopMessagesV2(GPTS.yemeksepetiws.GetTopMessagesV2Request request) {
            return base.Channel.GetTopMessagesV2(request);
        }
        
        public string GetTopMessagesV2(GPTS.yemeksepetiws.AuthHeader AuthHeader, int count) {
            GPTS.yemeksepetiws.GetTopMessagesV2Request inValue = new GPTS.yemeksepetiws.GetTopMessagesV2Request();
            inValue.AuthHeader = AuthHeader;
            inValue.count = count;
            GPTS.yemeksepetiws.GetTopMessagesV2Response retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).GetTopMessagesV2(inValue);
            return retVal.GetTopMessagesV2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.MessageSuccessfulResponse GPTS.yemeksepetiws.IntegrationSoap.MessageSuccessful(GPTS.yemeksepetiws.MessageSuccessfulRequest request) {
            return base.Channel.MessageSuccessful(request);
        }
        
        public void MessageSuccessful(GPTS.yemeksepetiws.AuthHeader AuthHeader, int messageId) {
            GPTS.yemeksepetiws.MessageSuccessfulRequest inValue = new GPTS.yemeksepetiws.MessageSuccessfulRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.messageId = messageId;
            GPTS.yemeksepetiws.MessageSuccessfulResponse retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).MessageSuccessful(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.UpdateOrderResponse GPTS.yemeksepetiws.IntegrationSoap.UpdateOrder(GPTS.yemeksepetiws.UpdateOrderRequest request) {
            return base.Channel.UpdateOrder(request);
        }
        
        public string UpdateOrder(GPTS.yemeksepetiws.AuthHeader AuthHeader, decimal orderId, GPTS.yemeksepetiws.OrderStates orderState, string reason) {
            GPTS.yemeksepetiws.UpdateOrderRequest inValue = new GPTS.yemeksepetiws.UpdateOrderRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.orderId = orderId;
            inValue.orderState = orderState;
            inValue.reason = reason;
            GPTS.yemeksepetiws.UpdateOrderResponse retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).UpdateOrder(inValue);
            return retVal.UpdateOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.UpdateValeOrderResponse GPTS.yemeksepetiws.IntegrationSoap.UpdateValeOrder(GPTS.yemeksepetiws.UpdateValeOrderRequest request) {
            return base.Channel.UpdateValeOrder(request);
        }
        
        public string UpdateValeOrder(GPTS.yemeksepetiws.AuthHeader AuthHeader, decimal orderId, GPTS.yemeksepetiws.OrderStates orderState, System.Nullable<PrepareTimes> prepareTime, string reason) {
            GPTS.yemeksepetiws.UpdateValeOrderRequest inValue = new GPTS.yemeksepetiws.UpdateValeOrderRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.orderId = orderId;
            inValue.orderState = orderState;
            inValue.prepareTime = prepareTime;
            inValue.reason = reason;
            GPTS.yemeksepetiws.UpdateValeOrderResponse retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).UpdateValeOrder(inValue);
            return retVal.UpdateValeOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.SetRestaurantForOrderResponse GPTS.yemeksepetiws.IntegrationSoap.SetRestaurantForOrder(GPTS.yemeksepetiws.SetRestaurantForOrderRequest request) {
            return base.Channel.SetRestaurantForOrder(request);
        }
        
        public bool SetRestaurantForOrder(GPTS.yemeksepetiws.AuthHeader AuthHeader, decimal orderId, string categoryName) {
            GPTS.yemeksepetiws.SetRestaurantForOrderRequest inValue = new GPTS.yemeksepetiws.SetRestaurantForOrderRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.orderId = orderId;
            inValue.categoryName = categoryName;
            GPTS.yemeksepetiws.SetRestaurantForOrderResponse retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).SetRestaurantForOrder(inValue);
            return retVal.SetRestaurantForOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.GetRestaurantListResponse GPTS.yemeksepetiws.IntegrationSoap.GetRestaurantList(GPTS.yemeksepetiws.GetRestaurantListRequest request) {
            return base.Channel.GetRestaurantList(request);
        }
        
        public System.Data.DataSet GetRestaurantList(GPTS.yemeksepetiws.AuthHeader AuthHeader) {
            GPTS.yemeksepetiws.GetRestaurantListRequest inValue = new GPTS.yemeksepetiws.GetRestaurantListRequest();
            inValue.AuthHeader = AuthHeader;
            GPTS.yemeksepetiws.GetRestaurantListResponse retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).GetRestaurantList(inValue);
            return retVal.GetRestaurantListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.UpdateRestaurantStateResponse GPTS.yemeksepetiws.IntegrationSoap.UpdateRestaurantState(GPTS.yemeksepetiws.UpdateRestaurantStateRequest request) {
            return base.Channel.UpdateRestaurantState(request);
        }
        
        public string UpdateRestaurantState(GPTS.yemeksepetiws.AuthHeader AuthHeader, string catalogName, string categoryName, GPTS.yemeksepetiws.RestaurantStates restaurantState) {
            GPTS.yemeksepetiws.UpdateRestaurantStateRequest inValue = new GPTS.yemeksepetiws.UpdateRestaurantStateRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.catalogName = catalogName;
            inValue.categoryName = categoryName;
            inValue.restaurantState = restaurantState;
            GPTS.yemeksepetiws.UpdateRestaurantStateResponse retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).UpdateRestaurantState(inValue);
            return retVal.UpdateRestaurantStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.IsRestaurantOpenResponse GPTS.yemeksepetiws.IntegrationSoap.IsRestaurantOpen(GPTS.yemeksepetiws.IsRestaurantOpenRequest request) {
            return base.Channel.IsRestaurantOpen(request);
        }
        
        public bool IsRestaurantOpen(GPTS.yemeksepetiws.AuthHeader AuthHeader, string catalogName, string categoryName) {
            GPTS.yemeksepetiws.IsRestaurantOpenRequest inValue = new GPTS.yemeksepetiws.IsRestaurantOpenRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.catalogName = catalogName;
            inValue.categoryName = categoryName;
            GPTS.yemeksepetiws.IsRestaurantOpenResponse retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).IsRestaurantOpen(inValue);
            return retVal.IsRestaurantOpenResult;
        }
        
        public GPTS.yemeksepetiws.RestaurantStatusEntity GetRestaurantStatus(string catalogName, string categoryName) {
            return base.Channel.GetRestaurantStatus(catalogName, categoryName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.SetRestaurantServiceTimeResponse GPTS.yemeksepetiws.IntegrationSoap.SetRestaurantServiceTime(GPTS.yemeksepetiws.SetRestaurantServiceTimeRequest request) {
            return base.Channel.SetRestaurantServiceTime(request);
        }
        
        public bool SetRestaurantServiceTime(GPTS.yemeksepetiws.AuthHeader AuthHeader, string catalogName, string categoryName, int serviceTime) {
            GPTS.yemeksepetiws.SetRestaurantServiceTimeRequest inValue = new GPTS.yemeksepetiws.SetRestaurantServiceTimeRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.catalogName = catalogName;
            inValue.categoryName = categoryName;
            inValue.serviceTime = serviceTime;
            GPTS.yemeksepetiws.SetRestaurantServiceTimeResponse retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).SetRestaurantServiceTime(inValue);
            return retVal.SetRestaurantServiceTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.GetMenuResponse GPTS.yemeksepetiws.IntegrationSoap.GetMenu(GPTS.yemeksepetiws.GetMenuRequest request) {
            return base.Channel.GetMenu(request);
        }
        
        public System.Data.DataSet GetMenu(GPTS.yemeksepetiws.AuthHeader AuthHeader) {
            GPTS.yemeksepetiws.GetMenuRequest inValue = new GPTS.yemeksepetiws.GetMenuRequest();
            inValue.AuthHeader = AuthHeader;
            GPTS.yemeksepetiws.GetMenuResponse retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).GetMenu(inValue);
            return retVal.GetMenuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.GetRestaurantPromotionsResponse GPTS.yemeksepetiws.IntegrationSoap.GetRestaurantPromotions(GPTS.yemeksepetiws.GetRestaurantPromotionsRequest request) {
            return base.Channel.GetRestaurantPromotions(request);
        }
        
        public System.Data.DataSet GetRestaurantPromotions(GPTS.yemeksepetiws.AuthHeader AuthHeader) {
            GPTS.yemeksepetiws.GetRestaurantPromotionsRequest inValue = new GPTS.yemeksepetiws.GetRestaurantPromotionsRequest();
            inValue.AuthHeader = AuthHeader;
            GPTS.yemeksepetiws.GetRestaurantPromotionsResponse retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).GetRestaurantPromotions(inValue);
            return retVal.GetRestaurantPromotionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.GetRestaurantPointsAndCommentsResponse GPTS.yemeksepetiws.IntegrationSoap.GetRestaurantPointsAndComments(GPTS.yemeksepetiws.GetRestaurantPointsAndCommentsRequest request) {
            return base.Channel.GetRestaurantPointsAndComments(request);
        }
        
        public System.Data.DataTable GetRestaurantPointsAndComments(GPTS.yemeksepetiws.AuthHeader AuthHeader, string catalogName, string categoryName, System.DateTime startDate, System.DateTime endDate) {
            GPTS.yemeksepetiws.GetRestaurantPointsAndCommentsRequest inValue = new GPTS.yemeksepetiws.GetRestaurantPointsAndCommentsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.catalogName = catalogName;
            inValue.categoryName = categoryName;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            GPTS.yemeksepetiws.GetRestaurantPointsAndCommentsResponse retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).GetRestaurantPointsAndComments(inValue);
            return retVal.GetRestaurantPointsAndCommentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.GetPaymentTypesResponse GPTS.yemeksepetiws.IntegrationSoap.GetPaymentTypes(GPTS.yemeksepetiws.GetPaymentTypesRequest request) {
            return base.Channel.GetPaymentTypes(request);
        }
        
        public System.Data.DataSet GetPaymentTypes(GPTS.yemeksepetiws.AuthHeader AuthHeader) {
            GPTS.yemeksepetiws.GetPaymentTypesRequest inValue = new GPTS.yemeksepetiws.GetPaymentTypesRequest();
            inValue.AuthHeader = AuthHeader;
            GPTS.yemeksepetiws.GetPaymentTypesResponse retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).GetPaymentTypes(inValue);
            return retVal.GetPaymentTypesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.GetRestaurantDeliveryAreasResponse GPTS.yemeksepetiws.IntegrationSoap.GetRestaurantDeliveryAreas(GPTS.yemeksepetiws.GetRestaurantDeliveryAreasRequest request) {
            return base.Channel.GetRestaurantDeliveryAreas(request);
        }
        
        public System.Data.DataSet GetRestaurantDeliveryAreas(GPTS.yemeksepetiws.AuthHeader AuthHeader, string catalogName, string categoryName) {
            GPTS.yemeksepetiws.GetRestaurantDeliveryAreasRequest inValue = new GPTS.yemeksepetiws.GetRestaurantDeliveryAreasRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.catalogName = catalogName;
            inValue.categoryName = categoryName;
            GPTS.yemeksepetiws.GetRestaurantDeliveryAreasResponse retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).GetRestaurantDeliveryAreas(inValue);
            return retVal.GetRestaurantDeliveryAreasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPTS.yemeksepetiws.UpdateRestaurantDeliveryAreaStateResponse GPTS.yemeksepetiws.IntegrationSoap.UpdateRestaurantDeliveryAreaState(GPTS.yemeksepetiws.UpdateRestaurantDeliveryAreaStateRequest request) {
            return base.Channel.UpdateRestaurantDeliveryAreaState(request);
        }
        
        public bool UpdateRestaurantDeliveryAreaState(GPTS.yemeksepetiws.AuthHeader AuthHeader, string catalogName, string categoryName, string areaId, bool isOpen) {
            GPTS.yemeksepetiws.UpdateRestaurantDeliveryAreaStateRequest inValue = new GPTS.yemeksepetiws.UpdateRestaurantDeliveryAreaStateRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.catalogName = catalogName;
            inValue.categoryName = categoryName;
            inValue.areaId = areaId;
            inValue.isOpen = isOpen;
            GPTS.yemeksepetiws.UpdateRestaurantDeliveryAreaStateResponse retVal = ((GPTS.yemeksepetiws.IntegrationSoap)(this)).UpdateRestaurantDeliveryAreaState(inValue);
            return retVal.UpdateRestaurantDeliveryAreaStateResult;
        }
        
        public string GetRestaurantOrderString(string eadres, string trackingNo, string password) {
            return base.Channel.GetRestaurantOrderString(eadres, trackingNo, password);
        }
    }
}
