//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sirketler
    {
        public int pkSirket { get; set; }
        public string Sirket { get; set; }
        public Nullable<int> Aktifyil { get; set; }
        public string TelefonNo { get; set; }
        public string Adres { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNo { get; set; }
        public string ServerAdi { get; set; }
        public string Yetkili { get; set; }
        public string yedekalinacakyer { get; set; }
        public string Yetkilikodu { get; set; }
        public Nullable<int> BarkodNo { get; set; }
        public Nullable<bool> WebKullanir { get; set; }
        public Nullable<bool> ParaPanelGoster { get; set; }
        public string Sektor { get; set; }
        public Nullable<short> FaturaTipi { get; set; }
        public Nullable<bool> StokTakibi { get; set; }
        public Nullable<bool> MusteriZorunluUyari { get; set; }
        public Nullable<bool> TedarikciZorunluUyari { get; set; }
        public Nullable<int> TeraziBarkoduBasi { get; set; }
        public Nullable<int> MusteriBasNo { get; set; }
        public string BarkodOzelKod { get; set; }
        public Nullable<int> BonusYuzde { get; set; }
        public string WebSitesi { get; set; }
        public Nullable<bool> Callerid { get; set; }
        public string Birimi { get; set; }
        public Nullable<int> BonusTur { get; set; }
        public string Host { get; set; }
        public string GonderenEposta { get; set; }
        public string GonderenEpostaSifre { get; set; }
        public string Port { get; set; }
        public string YedekSaati { get; set; }
        public string Fax { get; set; }
        public string Cep { get; set; }
        public string eposta { get; set; }
        public Nullable<int> stok_birimi { get; set; }
        public Nullable<int> kdv_orani { get; set; }
        public string sms_kullaniciadi { get; set; }
        public string sms_sifre { get; set; }
        public string sms_baslik { get; set; }
        public Nullable<bool> satisadedi_icindekiadetdir { get; set; }
        public string OzelSifre { get; set; }
        public Nullable<short> FaturaTipiAlis { get; set; }
        public Nullable<int> TeraziBarkoduBasi2 { get; set; }
        public Nullable<int> TeraziBarkoduBasi3 { get; set; }
        public Nullable<bool> ikincifiyatgoster { get; set; }
        public string KullaniciNo { get; set; }
        public string odemesekli { get; set; }
        public Nullable<bool> satiskopyala { get; set; }
        public Nullable<bool> uruneklendisescal { get; set; }
        public Nullable<bool> EnableSsl { get; set; }
        public Nullable<bool> OncekiFiyatHatirla { get; set; }
        public string yedek_alinacak_yer_paylasimli { get; set; }
        public string bccEposta { get; set; }
        public string ccEposta { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public string uretici__barkod_no { get; set; }
        public Nullable<bool> tedarikciler_giderdir { get; set; }
        public Nullable<int> is_kamp_odeme_sekli_acikhesap { get; set; }
        public Nullable<int> fkKodu { get; set; }
        public Nullable<int> fkAltGrup { get; set; }
        public Nullable<int> fkKoduDefault { get; set; }
        public Nullable<int> fkAltGrupDefault { get; set; }
        public Nullable<bool> DepoKullaniyorum { get; set; }
        public Nullable<bool> stok_karti_dizayn { get; set; }
        public Nullable<int> yedek_sil_gun { get; set; }
        public Nullable<int> fkBirimler { get; set; }
        public Nullable<System.DateTime> islem_tarihi { get; set; }
        public Nullable<int> ilktarih_devir_sontarih { get; set; }
        public string e_fatura_kul { get; set; }
        public string e_fatura_sifre { get; set; }
        public Nullable<int> kdv_orani_alis { get; set; }
        public Nullable<bool> oto_guncelle { get; set; }
        public Nullable<int> versiyon { get; set; }
        public Nullable<bool> ucuncufiyatgoster { get; set; }
        public Nullable<bool> makbuz_yazdir { get; set; }
    }
}
